# Generated by Django 2.2 on 2019-04-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('pokemon_name', models.CharField(max_length=255)),
                ('type_primary', models.CharField(max_length=255)),
                ('type_secondary', models.CharField(blank=True, max_length=255)),
                ('height', models.IntegerField(default=0)),
                ('height_units', models.CharField(default='inches', max_length=10)),
                ('weight', models.IntegerField(default=0)),
                ('weight_units', models.CharField(default='lbs', max_length=10)),
                ('pokedex_number', models.IntegerField(primary_key=True, serialize=False)),
                ('pokemon_image', models.URLField(blank=True)),
            ],
        ),
    ]
